apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-nginx
      tier: app
  template:
    metadata:
      labels:
        app: pod-nginx
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.5
          resources:
            limits:
              cpu: "1"
              memory: 1600Mi
            requests:
              cpu: 10m
              memory: 800Mi